# Generated by Django 5.2.6 on 2026-08-29 16:57

import django.core.validators
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reference', models.CharField(db_index=True, editable=False, max_length=12, unique=True)),
                ('date', models.DateField(db_index=True)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('duration_hours', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('starts_at', models.DateTimeField(db_index=True)),
                ('ends_at', models.DateTimeField(db_index=True)),
                ('hourly_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=14)),
                ('commission_percent', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5)),
                ('commission_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('owner_earning', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('currency', models.CharField(default='UZS', max_length=3)),
                ('status', models.CharField(choices=[('PENDING', 'Awaiting owner approval'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected by owner'), ('CANCELLED', 'Cancelled'), ('COMPLETED', 'Completed'), ('EXPIRED', 'Expired without a decision')], db_index=True, default='PENDING', max_length=9)),
                ('rejection_reason', models.CharField(blank=True, max_length=255)),
                ('cancellation_reason', models.CharField(blank=True, max_length=255)),
                ('customer_note', models.CharField(blank=True, max_length=255)),
                ('contact_phone', models.CharField(blank=True, max_length=13)),
                ('players_count', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejected_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ('-date', '-start_time'),
            },
        ),
        migrations.CreateModel(
            name='BookingStatusHistory',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('from_status', models.CharField(blank=True, max_length=9)),
                ('to_status', models.CharField(max_length=9)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
