# Generated by Django 5.2.6 on 2026-08-29 17:09

import apps.bookings.models
import django.contrib.postgres.constraints
import django.contrib.postgres.fields.ranges
from django.conf import settings
from django.contrib.postgres.operations import BtreeGistExtension
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_initial'),
        ('stadiums', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # btree_gist lets a GiST index mix the scalar `stadium` column with the
        # tstzrange, which is what makes the exclusion constraint possible.
        BtreeGistExtension(),
        migrations.AddConstraint(
            model_name='booking',
            constraint=django.contrib.postgres.constraints.ExclusionConstraint(condition=models.Q(('status__in', ['PENDING', 'APPROVED', 'COMPLETED'])), expressions=[(apps.bookings.models.TsTzRange('starts_at', 'ends_at', django.contrib.postgres.fields.ranges.RangeBoundary()), '&&'), ('stadium', '=')], name='booking_no_overlap'),
        ),
    ]
