# Generated by Django 5.2.6 on 2026-08-29 16:57

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('STADIUM_APPROVED', 'Stadium approved'), ('STADIUM_REJECTED', 'Stadium rejected'), ('STADIUM_BLOCKED', 'Stadium blocked'), ('STADIUM_CHANGES_REQUESTED', 'Changes requested'), ('USER_BLOCKED', 'User blocked'), ('USER_UNBLOCKED', 'User unblocked'), ('OWNER_CREATED', 'Owner created'), ('OWNER_UPDATED', 'Owner updated'), ('OWNER_DELETED', 'Owner deleted'), ('BOOKING_UPDATED', 'Booking updated'), ('BOOKING_CANCELLED', 'Booking cancelled'), ('REVIEW_HIDDEN', 'Review hidden'), ('REVIEW_RESTORED', 'Review restored'), ('SETTINGS_UPDATED', 'Settings updated')], db_index=True, max_length=40)),
                ('target_type', models.CharField(blank=True, max_length=60)),
                ('target_id', models.CharField(blank=True, db_index=True, max_length=64)),
                ('description', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='PlatformSetting',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.PositiveSmallIntegerField(default=1, editable=False, primary_key=True, serialize=False)),
                ('platform_name', models.CharField(default='Football Arena', max_length=120)),
                ('commission_percent', models.DecimalField(decimal_places=2, default=10, max_digits=5)),
                ('booking_cancel_window_hours', models.PositiveSmallIntegerField(default=3)),
                ('booking_max_advance_days', models.PositiveSmallIntegerField(default=60)),
                ('booking_min_duration_hours', models.PositiveSmallIntegerField(default=1)),
                ('booking_max_duration_hours', models.PositiveSmallIntegerField(default=6)),
                ('auto_approve_stadiums', models.BooleanField(default=False)),
                ('notifications_email_enabled', models.BooleanField(default=False)),
                ('notifications_telegram_enabled', models.BooleanField(default=False)),
                ('support_phone', models.CharField(blank=True, max_length=32)),
                ('support_email', models.EmailField(blank=True, max_length=254)),
                ('support_telegram', models.CharField(blank=True, max_length=64)),
                ('maintenance_mode', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Platform settings',
                'verbose_name_plural': 'Platform settings',
            },
        ),
    ]
