# Generated by Django 5.2.6 on 2026-08-29 16:57

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('BOOKING_CREATED', 'New booking request'), ('BOOKING_APPROVED', 'Booking approved'), ('BOOKING_REJECTED', 'Booking rejected'), ('BOOKING_CANCELLED', 'Booking cancelled'), ('BOOKING_COMPLETED', 'Booking completed'), ('BOOKING_REMINDER', 'Booking reminder'), ('STADIUM_SUBMITTED', 'Stadium awaiting approval'), ('STADIUM_APPROVED', 'Stadium approved'), ('STADIUM_REJECTED', 'Stadium rejected'), ('STADIUM_CHANGES_REQUESTED', 'Stadium changes requested'), ('NEW_MESSAGE', 'New chat message'), ('NEW_REVIEW', 'New review'), ('PAYMENT_SUCCESS', 'Payment succeeded'), ('PAYMENT_FAILED', 'Payment failed'), ('ACCOUNT_BLOCKED', 'Account blocked'), ('SYSTEM', 'System message')], db_index=True, max_length=32)),
                ('title', models.CharField(max_length=160)),
                ('message', models.TextField(blank=True)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('is_read', models.BooleanField(db_index=True, default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='NotificationDelivery',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('channel', models.CharField(choices=[('WEB', 'Web'), ('EMAIL', 'Email'), ('TELEGRAM', 'Telegram'), ('SMS', 'SMS')], max_length=8)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SENT', 'Sent'), ('FAILED', 'Failed'), ('SKIPPED', 'Skipped')], default='PENDING', max_length=8)),
                ('error', models.CharField(blank=True, max_length=255)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
