# Generated by Django 5.2.6 on 2026-08-29 16:57

import apps.users.models
import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('phone', models.CharField(blank=True, db_index=True, max_length=13, null=True, unique=True, validators=[django.core.validators.RegexValidator(message="Telefon raqam +998XXXXXXXXX formatida bo'lishi kerak.", regex='^\\+998\\d{9}$')])),
                ('email', models.EmailField(blank=True, db_index=True, max_length=254, null=True, unique=True)),
                ('username', models.CharField(blank=True, help_text='Used by owners and admins for password login.', max_length=32, null=True, unique=True, validators=[django.core.validators.RegexValidator(message="Login 4-32 belgidan iborat bo'lib, harf, raqam, _ . - dan tashkil topsin.", regex='^[a-zA-Z0-9_.-]{4,32}$')])),
                ('first_name', models.CharField(blank=True, max_length=60)),
                ('last_name', models.CharField(blank=True, max_length=60)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/%Y/%m/')),
                ('role', models.CharField(choices=[('ADMIN', 'Administrator'), ('OWNER', 'Stadium owner'), ('USER', 'Customer')], db_index=True, default='USER', max_length=8)),
                ('google_id', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('telegram_id', models.BigIntegerField(blank=True, null=True, unique=True)),
                ('telegram_username', models.CharField(blank=True, max_length=64)),
                ('language', models.CharField(default='uz', max_length=5)),
                ('is_active', models.BooleanField(default=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('is_blocked', models.BooleanField(db_index=True, default=False)),
                ('blocked_reason', models.CharField(blank=True, max_length=255)),
                ('blocked_at', models.DateTimeField(blank=True, null=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'ordering': ('-created_at',),
            },
            managers=[
                ('objects', apps.users.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='OTPCode',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('phone', models.CharField(db_index=True, max_length=13, validators=[django.core.validators.RegexValidator(message="Telefon raqam +998XXXXXXXXX formatida bo'lishi kerak.", regex='^\\+998\\d{9}$')])),
                ('code_hash', models.CharField(max_length=64)),
                ('purpose', models.CharField(choices=[('LOGIN', 'Login / registration'), ('PHONE_CHANGE', 'Phone number change')], default='LOGIN', max_length=16)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('is_used', models.BooleanField(default=False)),
                ('verification_token', models.CharField(blank=True, db_index=True, max_length=64)),
                ('verification_token_expires_at', models.DateTimeField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['phone', 'purpose', '-created_at'], name='users_otpco_phone_1936e6_idx'), models.Index(fields=['phone', 'is_used'], name='users_otpco_phone_067b2a_idx')],
            },
        ),
        migrations.CreateModel(
            name='OwnerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company_name', models.CharField(blank=True, max_length=150)),
                ('contact_phone', models.CharField(blank=True, max_length=13, validators=[django.core.validators.RegexValidator(message="Telefon raqam +998XXXXXXXXX formatida bo'lishi kerak.", regex='^\\+998\\d{9}$')])),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('telegram_contact', models.CharField(blank=True, max_length=64)),
                ('tax_id', models.CharField(blank=True, max_length=32)),
                ('payout_details', models.CharField(blank=True, max_length=255)),
                ('commission_percent', models.DecimalField(blank=True, decimal_places=2, help_text='Overrides the platform-wide commission when set.', max_digits=5, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_owners', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='owner_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('city', models.CharField(blank=True, max_length=80)),
                ('district', models.CharField(blank=True, max_length=80)),
                ('default_latitude', models.FloatField(blank=True, null=True)),
                ('default_longitude', models.FloatField(blank=True, null=True)),
                ('notify_web', models.BooleanField(default=True)),
                ('notify_email', models.BooleanField(default=False)),
                ('notify_telegram', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['role', 'is_blocked'], name='users_user_role_6ccd8b_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['-created_at'], name='users_user_created_5b2332_idx'),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.CheckConstraint(condition=models.Q(('phone__isnull', False), ('email__isnull', False), ('username__isnull', False), ('google_id__isnull', False), ('telegram_id__isnull', False), _connector='OR'), name='user_has_identifier'),
        ),
    ]
