# Generated by Django 5.2.6 on 2026-08-31 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='user',
            name='user_has_identifier',
        ),
        migrations.AddField(
            model_name='user',
            name='yandex_id',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.CheckConstraint(condition=models.Q(('phone__isnull', False), ('email__isnull', False), ('username__isnull', False), ('google_id__isnull', False), ('yandex_id__isnull', False), ('telegram_id__isnull', False), _connector='OR'), name='user_has_identifier'),
        ),
    ]
