# Generated by Django 5.2.6 on 2026-08-29 16:57

import apps.common.validators
import django.core.validators
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Amenity',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.SmallAutoField(primary_key=True, serialize=False)),
                ('code', models.SlugField(max_length=32, unique=True)),
                ('name', models.CharField(max_length=64)),
                ('name_uz', models.CharField(blank=True, max_length=64)),
                ('icon', models.CharField(blank=True, max_length=32)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'amenities',
                'ordering': ('sort_order', 'name'),
            },
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Stadium',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=140)),
                ('slug', models.SlugField(blank=True, max_length=170)),
                ('description', models.TextField(blank=True)),
                ('field_type', models.CharField(choices=[('MINI', 'Mini football'), ('F5', '5x5'), ('F7', '7x7'), ('F11', '11x11')], db_index=True, default='F5', max_length=6)),
                ('capacity', models.PositiveSmallIntegerField(default=10)),
                ('price_per_hour', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('country', models.CharField(default='Uzbekistan', max_length=60)),
                ('city', models.CharField(db_index=True, max_length=80)),
                ('district', models.CharField(blank=True, db_index=True, max_length=80)),
                ('address', models.CharField(max_length=255)),
                ('latitude', models.FloatField(validators=[apps.common.validators.validate_latitude])),
                ('longitude', models.FloatField(validators=[apps.common.validators.validate_longitude])),
                ('phone', models.CharField(blank=True, max_length=13)),
                ('status', models.CharField(choices=[('PENDING', 'Pending approval'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('BLOCKED', 'Blocked by admin')], db_index=True, default='PENDING', max_length=8)),
                ('moderation_note', models.TextField(blank=True, help_text='Reason for rejection or requested changes.')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('rating', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=3, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('5'))])),
                ('review_count', models.PositiveIntegerField(default=0)),
                ('booking_count', models.PositiveIntegerField(default=0)),
                ('view_count', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='StadiumBlackout',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(db_index=True)),
                ('start_time', models.TimeField(blank=True, help_text='Null blocks the whole day.', null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('reason', models.CharField(blank=True, max_length=160)),
            ],
            options={
                'ordering': ('date', 'start_time'),
            },
        ),
        migrations.CreateModel(
            name='StadiumImage',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='stadiums/%Y/%m/')),
                ('caption', models.CharField(blank=True, max_length=140)),
                ('is_cover', models.BooleanField(default=False)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ('-is_cover', 'sort_order', 'created_at'),
            },
        ),
        migrations.CreateModel(
            name='StadiumWorkingHour',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('weekday', models.PositiveSmallIntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')])),
                ('open_time', models.TimeField(default='08:00')),
                ('close_time', models.TimeField(default='23:00')),
                ('is_closed', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ('weekday',),
            },
        ),
    ]
