# Generated by Django 5.2.6 on 2026-08-29 16:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stadiums', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='favorite',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='stadium',
            name='amenities',
            field=models.ManyToManyField(blank=True, related_name='stadiums', to='stadiums.amenity'),
        ),
        migrations.AddField(
            model_name='stadium',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stadiums', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='stadium',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_stadiums', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='favorite',
            name='stadium',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='stadiums.stadium'),
        ),
        migrations.AddField(
            model_name='stadiumblackout',
            name='stadium',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blackouts', to='stadiums.stadium'),
        ),
        migrations.AddField(
            model_name='stadiumimage',
            name='stadium',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='stadiums.stadium'),
        ),
        migrations.AddField(
            model_name='stadiumworkinghour',
            name='stadium',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='working_hours', to='stadiums.stadium'),
        ),
        migrations.AddIndex(
            model_name='stadium',
            index=models.Index(fields=['status', 'is_active'], name='stadiums_st_status_448ce7_idx'),
        ),
        migrations.AddIndex(
            model_name='stadium',
            index=models.Index(fields=['latitude', 'longitude'], name='stadiums_st_latitud_9a2d1a_idx'),
        ),
        migrations.AddIndex(
            model_name='stadium',
            index=models.Index(fields=['city', 'district'], name='stadiums_st_city_63d406_idx'),
        ),
        migrations.AddIndex(
            model_name='stadium',
            index=models.Index(fields=['owner', 'status'], name='stadiums_st_owner_i_a72b48_idx'),
        ),
        migrations.AddIndex(
            model_name='stadium',
            index=models.Index(fields=['price_per_hour'], name='stadiums_st_price_p_985f79_idx'),
        ),
        migrations.AddIndex(
            model_name='stadium',
            index=models.Index(fields=['-rating'], name='stadiums_st_rating_3a58fd_idx'),
        ),
        migrations.AddConstraint(
            model_name='stadium',
            constraint=models.CheckConstraint(condition=models.Q(('price_per_hour__gte', 0)), name='stadium_price_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='stadium',
            constraint=models.CheckConstraint(condition=models.Q(('latitude__gte', -90), ('latitude__lte', 90)), name='stadium_latitude_range'),
        ),
        migrations.AddConstraint(
            model_name='stadium',
            constraint=models.CheckConstraint(condition=models.Q(('longitude__gte', -180), ('longitude__lte', 180)), name='stadium_longitude_range'),
        ),
        migrations.AddIndex(
            model_name='favorite',
            index=models.Index(fields=['user', '-created_at'], name='stadiums_fa_user_id_360643_idx'),
        ),
        migrations.AddConstraint(
            model_name='favorite',
            constraint=models.UniqueConstraint(fields=('user', 'stadium'), name='unique_user_favorite'),
        ),
        migrations.AddIndex(
            model_name='stadiumblackout',
            index=models.Index(fields=['stadium', 'date'], name='stadiums_st_stadium_7ec0e3_idx'),
        ),
        migrations.AddIndex(
            model_name='stadiumimage',
            index=models.Index(fields=['stadium', 'is_cover'], name='stadiums_st_stadium_57a89a_idx'),
        ),
        migrations.AddConstraint(
            model_name='stadiumworkinghour',
            constraint=models.UniqueConstraint(fields=('stadium', 'weekday'), name='unique_working_hour_per_weekday'),
        ),
    ]
