# Generated by Django 5.2.6 on 2026-08-29 16:57

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rating', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('comment', models.TextField(blank=True, max_length=1000)),
                ('owner_reply', models.TextField(blank=True, max_length=1000)),
                ('owner_replied_at', models.DateTimeField(blank=True, null=True)),
                ('is_visible', models.BooleanField(db_index=True, default=True)),
                ('hidden_reason', models.CharField(blank=True, max_length=255)),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='bookings.booking')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
