# Generated by Django 5.2.6 on 2026-08-29 16:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reviews', '0001_initial'),
        ('stadiums', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='stadium',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='stadiums.stadium'),
        ),
    ]
