# Generated by Django 5.2.6 on 2026-08-29 16:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('payments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='payout',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payouts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['booking', 'status'], name='payments_pa_booking_57d6de_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['provider', 'status'], name='payments_pa_provide_cc7861_idx'),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.UniqueConstraint(condition=models.Q(('transaction_id', ''), _negated=True), fields=('provider', 'transaction_id'), name='unique_provider_transaction'),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gte', 0)), name='payment_amount_non_negative'),
        ),
        migrations.AddIndex(
            model_name='payout',
            index=models.Index(fields=['owner', '-period_end'], name='payments_pa_owner_i_e21395_idx'),
        ),
    ]
